left:
  500     ## Variants below this size will be excluded

right:
  10000   ## Variants above this size will be excluded

overlap:
  0.5

vcfs: ## Paths to the vcf files.
   popdel: calls/popdel/platinum.popdel.vcf
   delly: calls/delly/platinum.delly.vcf
   lumpy: calls/lumpy/platinum.lumpy.vcf

truthSet: ## Choose only one! Double check that this is consistent with the truthFile below.
   personalis
#   pacbio

truthFile:  ## Choose only one!
   calls/reference/personalis/remapped_NA12878_personalis_deduplicated_deletions.sort.500-10000.bed
#   calls/reference/pacbio/remapped_NA12878_pacbio_deduplicated_deletions.sort.500-10000.bed

fullTruthFile: ## Ony neccessary for generous FP and FN counting
   calls/reference/personalis/remapped_NA12878_personalis_deduplicated_deletions.sort.all.bed
#   calls/reference/pacbio/remapped_NA12878_pacbio_deduplicated_deletions.sort.all.bed

centromereFile:
   calls/reference/centromeres.bed

filterCentromeres: ## Use "_noCentromeres" if you want to filter centromeres, otherwise use empty string.
   "_noCentromeres"
#   ""

outpath: ##Folder! Don't forget the trailing /
   calls/bed/
