left:
  500     ## Calls below this size will be excluded

right:
  10000   ## Calls above this size will be excluded

overlap:
  0.5

truthSet: ## Choose only one! Double check that this is consistent with the truthFile below.
   personalis
#   pacbio

truth:
   calls/reference/personalis/remapped_NA12878_personalis_deduplicated_deletions.sort.all.bed   ##Choose one. Must match above selection.
#   calls/reference/pacbio/remapped_NA12878_pacbio_deduplicated_deletions.sort.all.bed

centromereFile:
   calls/reference/centromeres.bed

vcfs: ## Paths to the vcf files.
   popdel: calls/popdel/platinum.popdel.vcf
   delly: calls/delly/platinum.delly.vcf
   smoove: calls/smoove/platinum.smoove.vcf.gz
   manta: calls/manta/platinum.manta.vcf.gz

outpath:
   eval
