name: delly
channels:
  - conda-forge
  - default
  - bioconda
  - r
  - defaults
dependencies:
  - bcftools=1.9
  - bzip2=1.0.6
  - ca-certificates=2019.9.11
  - curl=7.62.0
  - delly=0.7.8
  - gsl=2.5
  - htslib=1.9
  - icu=58.2
  - krb5=1.16.2
  - libblas=3.8.0
  - libboost=1.67.0
  - libcblas=3.8.0
  - libcurl=7.62.0
  - libdeflate=1.0
  - libedit=3.1.20170329
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libopenblas=0.3.7
  - libssh2=1.8.0
  - libstdcxx-ng=8.2.0
  - ncurses=6.1
  - openssl=1.0.2r
  - perl=5.26.2
  - tk=8.6.8
  - xz=5.2.4
  - zlib=1.2.11
