/usr/bin/time -f "1\t%e\t%U\t%S\t%M" -ao time/delly.time delly/0001.delly.sh
/usr/bin/time-f "10\t%e\t%U\t%S\t%M" -ao time/delly.time delly/0010.delly.sh
/usr/bin/time-f "20\t%e\t%U\t%S\t%M" -ao time/delly.time delly/0020.delly.sh
/usr/bin/time-f "30\t%e\t%U\t%S\t%M" -ao time/delly.time delly/0030.delly.sh
/usr/bin/time-f "40\t%e\t%U\t%S\t%M" -ao time/delly.time delly/0040.delly.sh
/usr/bin/time-f "50\t%e\t%U\t%S\t%M" -ao time/delly.time delly/0050.delly.sh
/usr/bin/time-f "60\t%e\t%U\t%S\t%M" -ao time/delly.time delly/0060.delly.sh
/usr/bin/time-f "70\t%e\t%U\t%S\t%M" -ao time/delly.time delly/0070.delly.sh
/usr/bin/time-f "80\t%e\t%U\t%S\t%M" -ao time/delly.time delly/0080.delly.sh
/usr/bin/time-f "90\t%e\t%U\t%S\t%M" -ao time/delly.time delly/0090.delly.sh
/usr/bin/time-f "100\t%e\t%U\t%S\t%M" -ao time/delly.time delly/0100.delly.sh
/usr/bin/time-f "200\t%e\t%U\t%S\t%M" -ao time/delly.time delly/0200.delly.sh
/usr/bin/time-f "300\t%e\t%U\t%S\t%M" -ao time/delly.time delly/0300.delly.sh
/usr/bin/time-f "400\t%e\t%U\t%S\t%M" -ao time/delly.time delly/0400.delly.sh
/usr/bin/time-f "500\t%e\t%U\t%S\t%M" -ao time/delly.time delly/0500.delly.sh
/usr/bin/time-f "600\t%e\t%U\t%S\t%M" -ao time/delly.time delly/0600.delly.sh
/usr/bin/time-f "700\t%e\t%U\t%S\t%M" -ao time/delly.time delly/0700.delly.sh
/usr/bin/time-f "800\t%e\t%U\t%S\t%M" -ao time/delly.time delly/0800.delly.sh
/usr/bin/time-f "900\t%e\t%U\t%S\t%M" -ao time/delly.time delly/0900.delly.sh
/usr/bin/time-f "1000\t%e\t%U\t%S\t%M" -ao time/delly.time delly/1000.delly.sh
