bamBase:
   /fast/work/groups/ag_kehr/data/GIAB/Ashkenazim_trio_HiSeq2500/bam

tmp:
   /fast/scratch/users/roskoscs_c/tmp/popdelGIAB

refVersion:
    GRCh37

samplingRegions:
   /fast/work/groups/ag_kehr/projects/2018-11-07_PopDelBenchmark/GIAB/scripts/popdel/sampling.regions   ## No longer necessary with version 1.1.3. use "-r grch37" instead

coverages:
  /fast/work/groups/ag_kehr/projects/2018-11-07_PopDelBenchmark/GIAB/scripts/popdel/maxCov.tsv

samples:
   - HG002
   - HG003
   - HG004

chromosomes:
   - 1
   - 2
   - 3
   - 4
   - 5
   - 6
   - 7
   - 8
   - 9
   - 10
   - 11
   - 12
   - 13
   - 14
   - 15
   - 16
   - 17
   - 18
   - 19
   - 20
   - 21
   - 22
