/usr/bin/time -f "1\t%e\t%U\t%S\t%M" -ao time/popdel.time popdel/0001.popdel.sh
/usr/bin/time -f "10\t%e\t%U\t%S\t%M" -ao time/popdel.time popdel/0010.popdel.sh
/usr/bin/time -f "20\t%e\t%U\t%S\t%M" -ao time/popdel.time popdel/0020.popdel.sh
/usr/bin/time -f "30\t%e\t%U\t%S\t%M" -ao time/popdel.time popdel/0030.popdel.sh
/usr/bin/time -f "40\t%e\t%U\t%S\t%M" -ao time/popdel.time popdel/0040.popdel.sh
/usr/bin/time -f "50\t%e\t%U\t%S\t%M" -ao time/popdel.time popdel/0050.popdel.sh
/usr/bin/time -f "60\t%e\t%U\t%S\t%M" -ao time/popdel.time popdel/0060.popdel.sh
/usr/bin/time -f "70\t%e\t%U\t%S\t%M" -ao time/popdel.time popdel/0070.popdel.sh
/usr/bin/time -f "80\t%e\t%U\t%S\t%M" -ao time/popdel.time popdel/0080.popdel.sh
/usr/bin/time -f "90\t%e\t%U\t%S\t%M" -ao time/popdel.time popdel/0090.popdel.sh
/usr/bin/time -f "100\t%e\t%U\t%S\t%M" -ao time/popdel.time popdel/0100.popdel.sh
/usr/bin/time -f "200\t%e\t%U\t%S\t%M" -ao time/popdel.time popdel/0200.popdel.sh
/usr/bin/time -f "300\t%e\t%U\t%S\t%M" -ao time/popdel.time popdel/0300.popdel.sh
/usr/bin/time -f "400\t%e\t%U\t%S\t%M" -ao time/popdel.time popdel/0400.popdel.sh
/usr/bin/time -f "500\t%e\t%U\t%S\t%M" -ao time/popdel.time popdel/0500.popdel.sh
/usr/bin/time -f "600\t%e\t%U\t%S\t%M" -ao time/popdel.time popdel/0600.popdel.sh
/usr/bin/time -f "700\t%e\t%U\t%S\t%M" -ao time/popdel.time popdel/0700.popdel.sh
/usr/bin/time -f "800\t%e\t%U\t%S\t%M" -ao time/popdel.time popdel/0800.popdel.sh
/usr/bin/time -f "900\t%e\t%U\t%S\t%M" -ao time/popdel.time popdel/0900.popdel.sh
/usr/bin/time -f "1000\t%e\t%U\t%S\t%M" -ao time/popdel.time popdel/1000.popdel.sh
