projectName:
   giab
environment:
   manta.env
refVersion:
   GRCh37
reference:
   data/GIAB/Ashkenazim_trio_HiSeq2500/reflinks/hs37d5.fa
bamBase:
   data/GIAB/Ashkenazim_trio_HiSeq2500/bam
wd:
   tmp/manta/giab
vcf:
   - calls/manta/all.manta.GRCh37.vcf.gz
   - calls/manta/HG002.manta.GRCh37.vcf.gz
samples:
   - HG002
   - HG003
   - HG004
